/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export customer transactions
         * @description Generates a CSV export for the specified customer's transactions.
         *     Returns metadata about the export result (row count, success status).
         */
        post: operations["exportTransactions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ExportRequest: {
            /** @description Customer identifier to export transactions for */
            customer: string;
            /** @description Optional start date filter (ISO 8601) */
            startDate?: string;
            /** @description Optional end date filter (ISO 8601) */
            endDate?: string;
            /**
             * @description Output format (defaults to csv)
             * @enum {string}
             */
            format?: "csv" | "json";
        };
        ExportSuccessResponse: {
            /** @enum {boolean} */
            success: true;
            /** @description Number of transaction rows exported */
            rowCount: number;
            /** @description Human-readable status message */
            message: string;
        };
        ErrorResponse: {
            /** @description Human-readable error message */
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    exportTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Export completed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportSuccessResponse"];
                };
            };
            /** @description Invalid request (e.g. missing customer) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error or export failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
